---
- name: Update System
  become: yes
  apt:
    update_cache: yes

- name: Install Enchant 
  become: yes
  apt:
    name: enchant
    state: latest

- name: Create nltk_data directory in /home/ubuntu
  file:
    path: /home/ubuntu/nltk_data
    state: directory

- name: Install Required Modules
  become: yes
  pip: 
    name: '{{ item }}'
    executable: pip3
  loop:
    - tweepy
    - CouchDB
    - inflection
    - pyenchant
    - textblob

- name: Download textblob corpus data
  become: yes
  command: python3 -m textblob.download_corpora
  register: whatishere
  environment:
    NLTK_DATA: /home/ubuntu/nltk_data

- name: Print out output
  debug:
    msg: "{{ whatishere }}"

- name: Remove default constants.py file to apply Twitter Credentials in variables/twitterdetails.yaml
  become: yes
  command: rm /home/ubuntu/SinsOnTwitter/src/tweet_collector/constants.py

- name: Template the new constants.py with new twitter Credentials
  become: yes
  template:
    src: templates/constants.py
    dest: /home/ubuntu/SinsOnTwitter/src/tweet_collector/constants.py

- name: Run Twitter Harvesters in Background
  become: yes
  shell: nohup python3 /home/ubuntu/SinsOnTwitter/src/tweet_collector/collect_sin_streaming.py {{couchdb_url}} {{couchdb_user}} {{couchdb_pass}} > /dev/null 2>&1 &

