---
- name: Create a security group
  os_security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  loop: '{{ security_groups }}'

- name: Adding couchDB_rules to ansible_CouchDB group
  os_security_group_rule:
    security_group: 'ansible_CouchDB'
    protocol: '{{ item.protocol }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_ip_prefix: '{{ item.remote_ip_prefix }}'
    state: present
  loop: '{{ couchDB_rules }}'

- name: Create a list of security group names
  set_fact:
    sg_names: '{{ sg_names|default([]) + [item.name] }}'
  loop: '{{ security_groups }}'

- name: Printing Created Security Groups...
  debug:
    msg: "Security Groups {{ sg_names }} have been created."