# Common Vars
availability_zone: melbourne-qh2-uom

#Volumes 
volumes:
  - vol_name: demo_vol_one
    vol_size: 5
  - vol_name: demo_vol_two
    vol_size: 5

#Security Groups
security_groups:
  - name: internal #Already Created Previously for static system
    description: "Internal Access Between Nodes"
  - name: ssh
    description: "SSH Access via port 22"
  - name: http
    description: "HTTP Access via port 80"
  - name: ansible_CouchDB
    description: "Opening Ports for CouchDB Access"

#Rules for the couchdb_ports group
couchDB_rules:
  - name: ansible_Port 5984
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: ansible_Port 4369
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: ansible_Port 4369
    protocol: tcp
    port_range_min: 5986
    port_range_max: 5986
    remote_ip_prefix: 0.0.0.0/0
  - name: ansible_Ports 9100-9200
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0

#Instances To be Created 
#(Add Instances here to be created)
instance_list: 
    # Choose one of them to be the master
  - name: db_master
    instance_name: db_master
    instance_image: 955a0556-1224-4499-a895-87d54d5cbf32 #Ubuntu 18.04 Bionic amd64
    instance_key_name: Group68KeyPair
    instance_flavor: uom.general.1c4g  
  - name: db_slave_one
    instance_name: db_slave_one
    instance_image: 955a0556-1224-4499-a895-87d54d5cbf32 #Ubuntu 18.04 Bionic amd64
    instance_key_name: Group68KeyPair
    instance_flavor: uom.general.1c4g  