---
- name: Appending Proxy Configurations to Environment File
  become: yes
  lineinfile:
    line: "{{ item }}"
    state: present
    path: "/etc/environment"
  with_items:
    - 'http_proxy="http://wwwproxy.unimelb.edu.au:8000"'
    - 'https_proxy="http://wwwproxy.unimelb.edu.au:8000"'
    - 'ftp_proxy="http://wwwproxy.unimelb.edu.au:8000"'
    - 'no_proxy=localhost,127.0.0.1,127.0.1.1,Ubuntu'

- name: Reboot After Environment Proxy Setup
  become: yes
  reboot:
    reboot_timeout: 300

