---
- name: Cluster Setup Part 1
  command: curl -XPOST "http://{{couchdb_user}}:{{couchdb_pass}}@{{masternode}}:5984/_cluster_setup" --header "Content-Type:application/json" --data "{\"action\":\"enable_cluster\", \"bind_address\":\"0.0.0.0\", \"username\":\"{{couchdb_user}}\", \"password\":\"{{couchdb_pass}}\", \"port\":\"5984\", \"node_count\":\"{{node_count}}\", \"remote_node\":\"{{ item }}\", \"remote_current_user\":\"{{couchdb_user}}\", \"remote_current_password\":\"{{couchdb_pass}}\"}"
  loop: "{{ groups['workerservers'] }}"
  when: item != "{{ groups['workerservers'][0] }}"

- name: Cluster Setup Part 2 
  command: curl -XPOST "http://{{couchdb_user}}:{{couchdb_pass}}@{{masternode}}:5984/_cluster_setup" --header "Content-Type:application/json" --data "{\"action\":\"add_node\", \"host\":\"{{ item }}\", \"port\":\"5984\", \"username\":\"{{couchdb_user}}\", \"password\":\"{{couchdb_pass}}\"}"
  loop: "{{ groups['workerservers'] }}"
  when: item != "{{ groups['workerservers'][0] }}"

- name: Finish Cluster Setup
  command: curl -XPOST "http://{{couchdb_user}}:{{couchdb_pass}}@{{masternode}}:5984/_cluster_setup" \--header "Content-Type:application/json" --data "{\"action\":\"finish_cluster\"}" 

- name: Get Membership Details
  uri: 
    url: http://{{couchdb_user}}:{{couchdb_pass}}@{{masternode}}:5984/_membership/
    method: GET
    user: '{{couchdb_user}}'
    password: '{{couchdb_pass}}'
  register: membership_response

- name: Print Successful Membership Response
  debug:
    msg: "{{ membership_response.json }}" 

