---
- name: Update Machine 
  become: yes
  apt:
    update_cache: yes

- name: Install Python3
  become: yes
  apt:
    name: python3
    state: latest

- name: Install pip3
  become: yes
  apt:
    name: python3-pip
    state: latest

- name: Install Curl
  become: yes
  apt:
    name: curl
    state: latest
    
- name: Install JQ
  become: yes 
  apt:
    name: jq  
    state: latest

- name: Install Docker
  become: yes
  apt:
    name: docker.io

- name: Clone Project Repository
  git:
    repo: https://{{gitUsername}}:{{gitPassword}}@{{gitProjectURL}}
    dest: /home/ubuntu/SinsOnTwitter/
    version: '{{ branch }}'



