---
- name: Update Machine 
  become: yes
  apt:
    update_cache: yes

- name: Install Python3
  become: yes
  apt:
    name: python3
    state: latest

- name: Install pip3
  become: yes
  apt:
    name: python3-pip
    state: latest

- name: Install Docker
  become: yes
  apt:
    name: docker.io