# Deploying instances and security groups
- name: Creating Instances On Nectar
  hosts: localhost
  vars_files:
    - variables/instancedetails.yml
  gather_facts: true
  roles:
   - role: hostPreInstall
   - role: createSecurityGroups
   - role: createInstances
   - role: createVolumes



