---
#Playbook that Sets up common setup for all instances
- name: Common Setup Tasks Between all Instances
  hosts: workerservers:webserver
  sudo: yes
  gather_facts: no
  vars_files:
     - variables/gitDetails.yaml
  pre_tasks:
     - name: Wait 600 seconds for target connection to become reachable/usable
       wait_for_connection:
  roles:
     - role: vmSetup
     - role: installingSoftware
     - role: configureDocker
