#Setting up and configuring each instance
- name: Common Tasks Between all Instances
  hosts: servers
  sudo: yes
  gather_facts: no
  pre_tasks:
     - pause:
          prompt: "Making sure that instances are setup before accessing them..."
          minutes: 5
     - debug: var=ansible_default_ipv4.address
  roles:
     - role: vmSetup
     - role: installingSoftware
     - role: configureDocker

#Setting Up CouchDB on all db servers
- name: Setting Up CouchDB Slaves
  hosts: dbservers
  gather_facts: yes
  sudo: yes
  roles:
     - role: configureCouchDB_Common

#Preparing Cluster Setup by Running Commands on Master
#Set the first IP in dbservers as the Master
- name: Setting Up Master
  hosts: dbservers[0]
  gather_facts: yes
  sudo: yes
  roles:
     #- role: configureCouchDB_Cluster