---
#Preparing Cluster Setup by Running Commands on Master
#Set the first IP in dbservers as the Master
- name: Configuring Cluster Setup from Master Node
  hosts: dbservers[0]
  vars_files:
    - variables/couchdbDetails.yaml
  gather_facts: yes
  sudo: yes
  roles:
     - role: configureCouchDB_Cluster