---
- name: Create all instances
  os_server:
    name: '{{ item.instance_name }}'
    image: '{{ item.instance_image }}'
    key_name: '{{ item.instance_key_name }}'
    flavor: '{{ item.instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  with_items: '{{ instance_list }}'
  register: 'instances'

- name: Put IP Address of instance into inventory file
  lineinfile: 
    path: /mnt/c/DOCUMENTS/Masters Sem 2/Cluster and Cloud Computing/Assignment2/SinsOnTwitter/Ansible/inventory.ini
    line: '{{ item.openstack.public_v4 }}' 
    insertafter: '\[servers\]'
  with_items: '{{ instances.results }}'
